// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

/*
Package consolepb is a generated protocol buffer package.

It is generated from these files:
	manager.proto

It has these top-level messages:
	NodeName
	NodesStatus
	Node
	NodesState
	Result
	ReplayContent
	SessionUsers
*/
package consolepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeName struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *NodeName) Reset()                    { *m = NodeName{} }
func (m *NodeName) String() string            { return proto.CompactTextString(m) }
func (*NodeName) ProtoMessage()               {}
func (*NodeName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NodesStatus struct {
	NodesStatus map[string]int32 `protobuf:"bytes,1,rep,name=nodesStatus" json:"nodesStatus,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *NodesStatus) Reset()                    { *m = NodesStatus{} }
func (m *NodesStatus) String() string            { return proto.CompactTextString(m) }
func (*NodesStatus) ProtoMessage()               {}
func (*NodesStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodesStatus) GetNodesStatus() map[string]int32 {
	if m != nil {
		return m.NodesStatus
	}
	return nil
}

type Node struct {
	Name     string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Driver   string            `protobuf:"bytes,2,opt,name=driver" json:"driver,omitempty"`
	Params   map[string]string `protobuf:"bytes,3,rep,name=params" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ondemand bool              `protobuf:"varint,4,opt,name=ondemand" json:"ondemand,omitempty"`
	Status   int32             `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Node) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Node) GetOndemand() bool {
	if m != nil {
		return m.Ondemand
	}
	return false
}

func (m *Node) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type NodesState struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	State string   `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
}

func (m *NodesState) Reset()                    { *m = NodesState{} }
func (m *NodesState) String() string            { return proto.CompactTextString(m) }
func (*NodesState) ProtoMessage()               {}
func (*NodesState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodesState) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *NodesState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type Result struct {
	Result map[string]string `protobuf:"bytes,1,rep,name=result" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Result) GetResult() map[string]string {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReplayContent struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *ReplayContent) Reset()                    { *m = ReplayContent{} }
func (m *ReplayContent) String() string            { return proto.CompactTextString(m) }
func (*ReplayContent) ProtoMessage()               {}
func (*ReplayContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReplayContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SessionUsers struct {
	Users []string `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *SessionUsers) Reset()                    { *m = SessionUsers{} }
func (m *SessionUsers) String() string            { return proto.CompactTextString(m) }
func (*SessionUsers) ProtoMessage()               {}
func (*SessionUsers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SessionUsers) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeName)(nil), "consolepb.NodeName")
	proto.RegisterType((*NodesStatus)(nil), "consolepb.NodesStatus")
	proto.RegisterType((*Node)(nil), "consolepb.Node")
	proto.RegisterType((*NodesState)(nil), "consolepb.NodesState")
	proto.RegisterType((*Result)(nil), "consolepb.Result")
	proto.RegisterType((*ReplayContent)(nil), "consolepb.ReplayContent")
	proto.RegisterType((*SessionUsers)(nil), "consolepb.SessionUsers")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ConsoleManager service

type ConsoleManagerClient interface {
	ShowNode(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*Node, error)
	SetConsoleState(ctx context.Context, in *NodesState, opts ...grpc.CallOption) (*Result, error)
	GetReplayContent(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*ReplayContent, error)
	ListSessionUser(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*SessionUsers, error)
	ListNodesStatus(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*NodesStatus, error)
}

type consoleManagerClient struct {
	cc *grpc.ClientConn
}

func NewConsoleManagerClient(cc *grpc.ClientConn) ConsoleManagerClient {
	return &consoleManagerClient{cc}
}

func (c *consoleManagerClient) ShowNode(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := grpc.Invoke(ctx, "/consolepb.ConsoleManager/ShowNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleManagerClient) SetConsoleState(ctx context.Context, in *NodesState, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/consolepb.ConsoleManager/SetConsoleState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleManagerClient) GetReplayContent(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*ReplayContent, error) {
	out := new(ReplayContent)
	err := grpc.Invoke(ctx, "/consolepb.ConsoleManager/GetReplayContent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleManagerClient) ListSessionUser(ctx context.Context, in *NodeName, opts ...grpc.CallOption) (*SessionUsers, error) {
	out := new(SessionUsers)
	err := grpc.Invoke(ctx, "/consolepb.ConsoleManager/ListSessionUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleManagerClient) ListNodesStatus(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*NodesStatus, error) {
	out := new(NodesStatus)
	err := grpc.Invoke(ctx, "/consolepb.ConsoleManager/ListNodesStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConsoleManager service

type ConsoleManagerServer interface {
	ShowNode(context.Context, *NodeName) (*Node, error)
	SetConsoleState(context.Context, *NodesState) (*Result, error)
	GetReplayContent(context.Context, *NodeName) (*ReplayContent, error)
	ListSessionUser(context.Context, *NodeName) (*SessionUsers, error)
	ListNodesStatus(context.Context, *google_protobuf.Empty) (*NodesStatus, error)
}

func RegisterConsoleManagerServer(s *grpc.Server, srv ConsoleManagerServer) {
	s.RegisterService(&_ConsoleManager_serviceDesc, srv)
}

func _ConsoleManager_ShowNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleManagerServer).ShowNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consolepb.ConsoleManager/ShowNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleManagerServer).ShowNode(ctx, req.(*NodeName))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleManager_SetConsoleState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodesState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleManagerServer).SetConsoleState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consolepb.ConsoleManager/SetConsoleState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleManagerServer).SetConsoleState(ctx, req.(*NodesState))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleManager_GetReplayContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleManagerServer).GetReplayContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consolepb.ConsoleManager/GetReplayContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleManagerServer).GetReplayContent(ctx, req.(*NodeName))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleManager_ListSessionUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleManagerServer).ListSessionUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consolepb.ConsoleManager/ListSessionUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleManagerServer).ListSessionUser(ctx, req.(*NodeName))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleManager_ListNodesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleManagerServer).ListNodesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consolepb.ConsoleManager/ListNodesStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleManagerServer).ListNodesStatus(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsoleManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consolepb.ConsoleManager",
	HandlerType: (*ConsoleManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowNode",
			Handler:    _ConsoleManager_ShowNode_Handler,
		},
		{
			MethodName: "SetConsoleState",
			Handler:    _ConsoleManager_SetConsoleState_Handler,
		},
		{
			MethodName: "GetReplayContent",
			Handler:    _ConsoleManager_GetReplayContent_Handler,
		},
		{
			MethodName: "ListSessionUser",
			Handler:    _ConsoleManager_ListSessionUser_Handler,
		},
		{
			MethodName: "ListNodesStatus",
			Handler:    _ConsoleManager_ListNodesStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x6d, 0x8b, 0xd3, 0x40,
	0x10, 0x6e, 0xfa, 0x12, 0x9b, 0xa9, 0x67, 0xeb, 0xaa, 0x35, 0xe4, 0x50, 0xca, 0x22, 0x58, 0xbf,
	0xe4, 0xa0, 0x87, 0x70, 0x0a, 0x0a, 0x52, 0x0e, 0x11, 0xf4, 0x90, 0x14, 0x7f, 0xc0, 0xf6, 0x3a,
	0xd6, 0x62, 0xb2, 0x1b, 0xb2, 0x9b, 0x93, 0xfa, 0x4b, 0xfc, 0x59, 0x7e, 0xf2, 0xf7, 0xc8, 0xbe,
	0xb4, 0x6e, 0x6b, 0x40, 0xfc, 0x94, 0x79, 0x36, 0xcf, 0xcc, 0x3c, 0xcf, 0xec, 0x0e, 0x9c, 0x14,
	0x8c, 0xb3, 0x35, 0x56, 0x69, 0x59, 0x09, 0x25, 0x48, 0x74, 0x2d, 0xb8, 0x14, 0x39, 0x96, 0xcb,
	0xe4, 0x74, 0x2d, 0xc4, 0x3a, 0xc7, 0x33, 0xf3, 0x63, 0x59, 0x7f, 0x3e, 0xc3, 0xa2, 0x54, 0x5b,
	0xcb, 0xa3, 0x8f, 0xa1, 0x7f, 0x25, 0x56, 0x78, 0xc5, 0x0a, 0x24, 0x04, 0xba, 0x9c, 0x15, 0x18,
	0x07, 0x93, 0x60, 0x1a, 0x65, 0x26, 0xa6, 0x3f, 0x02, 0x18, 0x68, 0x82, 0x5c, 0x28, 0xa6, 0x6a,
	0x49, 0xde, 0xc1, 0x80, 0xff, 0x81, 0x71, 0x30, 0xe9, 0x4c, 0x07, 0xb3, 0xa7, 0xe9, 0xbe, 0x5b,
	0xea, 0x91, 0xfd, 0xf8, 0x92, 0xab, 0x6a, 0x9b, 0xf9, 0xb9, 0xc9, 0x6b, 0x18, 0x1d, 0x13, 0xc8,
	0x08, 0x3a, 0x5f, 0x71, 0xeb, 0x14, 0xe8, 0x90, 0xdc, 0x87, 0xde, 0x0d, 0xcb, 0x6b, 0x8c, 0xdb,
	0x93, 0x60, 0xda, 0xcb, 0x2c, 0x78, 0xd9, 0xbe, 0x08, 0xe8, 0xaf, 0x00, 0xba, 0xba, 0x40, 0x93,
	0x6e, 0x32, 0x86, 0x70, 0x55, 0x6d, 0x6e, 0xb0, 0x32, 0x79, 0x51, 0xe6, 0x10, 0x39, 0x87, 0xb0,
	0x64, 0x15, 0x2b, 0x64, 0xdc, 0x31, 0xd2, 0x4f, 0x8f, 0xa4, 0xa7, 0x1f, 0xcd, 0x5f, 0x2b, 0xd7,
	0x51, 0x49, 0x02, 0x7d, 0xc1, 0x57, 0x58, 0x30, 0xbe, 0x8a, 0xbb, 0x93, 0x60, 0xda, 0xcf, 0xf6,
	0x58, 0x37, 0x92, 0x76, 0x16, 0x3d, 0x23, 0xd0, 0xa1, 0xe4, 0x05, 0x0c, 0xbc, 0x52, 0xff, 0x32,
	0x16, 0xf9, 0xc6, 0x2e, 0x00, 0xf6, 0x83, 0x41, 0xcd, 0xd3, 0x8e, 0xec, 0xac, 0xa3, 0xcc, 0x02,
	0x7d, 0xaa, 0x1b, 0xed, 0xb3, 0x0d, 0xa0, 0xdf, 0x21, 0xcc, 0x50, 0xd6, 0xb9, 0x22, 0xcf, 0x21,
	0xac, 0x4c, 0xe4, 0xae, 0xe8, 0x91, 0xe7, 0xd3, 0x52, 0xdc, 0xc7, 0x39, 0xb5, 0x64, 0xad, 0xda,
	0x3b, 0xfe, 0x2f, 0xd5, 0xcf, 0xe0, 0x24, 0xc3, 0x32, 0x67, 0xdb, 0xb9, 0xe0, 0x0a, 0xb9, 0x22,
	0x31, 0xdc, 0xba, 0xb6, 0xa1, 0x2b, 0xb0, 0x83, 0xf4, 0x09, 0xdc, 0x5e, 0xa0, 0x94, 0x1b, 0xc1,
	0x3f, 0x49, 0xac, 0x8c, 0x99, 0x5a, 0x07, 0x3b, 0x8b, 0x06, 0xcc, 0x7e, 0xb6, 0xe1, 0xce, 0xdc,
	0x8a, 0xfe, 0x60, 0xdf, 0x36, 0x99, 0x41, 0x7f, 0xf1, 0x45, 0x7c, 0x33, 0xb7, 0x7e, 0xef, 0xe8,
	0xe6, 0xf4, 0x13, 0x4e, 0x86, 0x47, 0x87, 0xb4, 0x45, 0x5e, 0xc1, 0x70, 0x81, 0xca, 0x15, 0xb2,
	0x23, 0x7d, 0xd0, 0xf4, 0x5e, 0x31, 0xb9, 0xfb, 0xd7, 0x8c, 0x68, 0x8b, 0xcc, 0x61, 0xf4, 0x16,
	0xd5, 0xa1, 0xb3, 0xc6, 0xd6, 0xf1, 0x41, 0xb6, 0x47, 0xa7, 0x2d, 0xf2, 0x06, 0x86, 0xef, 0x37,
	0x52, 0x79, 0xa6, 0x9b, 0x6b, 0x3c, 0xf4, 0x0e, 0xfd, 0x09, 0x19, 0x1d, 0xa6, 0x84, 0xbf, 0x8b,
	0xe3, 0xd4, 0x6e, 0x76, 0xba, 0xdb, 0xec, 0xf4, 0x52, 0x6f, 0x76, 0x32, 0x6e, 0x5e, 0x47, 0xda,
	0x5a, 0x86, 0x86, 0x79, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x39, 0xc1, 0x68, 0xc4, 0x2d, 0x04,
	0x00, 0x00,
}
